apiVersion: v1
kind: PersistentVolume
metadata:
  name: yugabyte-db-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  hostPath:
    path: /mnt/data
  storageClassName: manual
